version: '3.3'

services:
  apigive-postgress:
    image: postgres
    container_name: apigive-postgress
    environment:
      - POSTGRES_DB=apigive
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5443:5432"
    volumes:
      - apigive-db-data:/var/lib/postgresql/data

  apigive-postgress-test:
    # CAUTION: Running tests will delete all records of this db, so just use this container for test
    # For running application use above container port: 5442
    image: postgres
    container_name: apigive-postgress-test
    environment:
      - POSTGRES_DB=givethio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5444:5432"
    volumes:
      - apigive-db-data-test:/var/lib/postgresql/data

  apigive-redis:
    # it's better to not using latest tag, maybe latest tag have some breaking changes
    image: bitnami/redis:5.0.9-debian-10-r142
    container_name: apigive-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    ports:
      - "6489:6379"
    volumes:
      - apigive-redis-data:/bitnami/redis/data

volumes:
  apigive-db-data:
  apigive-db-data-test:
  apigive-redis-data:
